### PR TITLE
84/major refactor

### PR DESCRIPTION
**Pull request by stevenshih1997**
…ition; small docker-compose change

SHOULD merge this first before other PRs affecting front end.

Restructure front end files; Make use of reusable components in future pull requests, as well as separate out logic. components and containers should be reusable,  and views are composed of the above. Feel free to add or remove things I might be missing.
Utilize more of a functional approach for easier future development. We can settle on Javascript/React stylistic conventions with the .eslintrc file at the root of the client folder. Maybe add webpack to help with css management in future ticket.

### CODE REVIEW

**Review by cowmanjoe — COMMENTED** [review]
Looks good to me, although I am not very involved with the front end, and am not super familiar with how react projects are structured. Three things jumped out at me though: 
1. This PR is into develop. I thought we were merging things into integration first before moving to develop. 
2. There is no search button in the nav bar anymore contrary to what is on integration now. 
3. There is a .gitkeep file in the components folder that is unnecessary.

**Comment by stevenshih1997** [comment]
Yeah, I'll take a look at the search button. I branched off of develop, so that might not contain the search button in the first place. I was thinking maybe having both develop and integration is a bit cumbersome. We would have to make sure more things are in sync and wouldn't the develop branch simply act as another master branch in this case?

**Comment by cowmanjoe** [comment]
@DConnorFong I kinda agree with Steven at this point in the project. I think that having integration set up makes sense for a long ongoing project that has a ton of commits already. Since we are just starting out though, I think that the integration branch is a bit cumbersome especially when we are making big changes. Since we are not supposed to branch off of integration I think it can be hard to build on top of what other people are doing especially when we are making pretty big changes such as folder structure and other big refactorings of the project. 

I think it is fine at this point for us to just make PRs to develop and branch off of that for features.

**Comment by DConnorFong** [comment]
@cowmanjoe I agree too, when I first proposed this, I didn't really think about the difference in what you see in commits on an enterprise application vs a starting project.

**Review by kimoantiqe — APPROVED** [review]
Tested Docker files locally and they all work !! ,
I think something to consider in the future would be pushing our docker images to azure’s container registry (or wtv cloud we are using) instead of docker hub. Doing this would allow for faster deployments and higher maintainability ( since our images would be stored next to the respective data center of our choosing).. But as of now dockerhub is good enough (until we figure out where are we deploying ofcourse)

**Comment by frostyshadows** [comment]
Agree with @stevenshih1997 and @cowmanjoe that having both develop and integration isn't really necessary. Even for most of the bigger enterprise-level projects I've worked on during co-op, having release and develop branches was enough.

**Comment by DConnorFong** [comment]
@frostyshadows eh, I agree that its not appropriate right now at this stage of the project but I wouldn't go that far lol

**Comment by stevenshih1997** [comment]
I'll hold off on merging until this Saturday at the meeting, and see how the integration and develop branch should be merged together. I believe they're currently out of sync, with both having commits the other doesn't.

**Comment by DConnorFong** [comment]
@stevenshih1997 I believe most tickets have finished integration and are already back in develop. The rest should be on the remote and can be merged in to integration manually. It should be fine to merge this to develop whenever you are ready.

**Comment by stevenshih1997** [comment]
I checked integration, and there's actually a few differences. There's no router nor home page in develop. And little changes such as the search button and the logo.

**Pull request merged**
