### PR TITLE
Feature/76 search filter

### PR DESCRIPTION
**Pull request by frostyshadows**
Finished React/CSS part of search filter, based on Stephanie's designs: https://www.fluidui.com/editor/live/preview/cF9Oazdja0hzQ1BXc0kwMVVaeFpMQ000Q2JKVEtlREZTTg==

Right now, it looks fine on fullscreen mode but doesn't look good on mobile/narrow screens.

screen shot 2018-11-02 at 9 18 55 pm

### CODE REVIEW

**Comment by frostyshadows** [comment]
Merging this into develop is gonna be fun lol

**Comment by stephqwu** [comment]
Lol I think you might get conflicts with https://github.com/ubclaunchpad/Internado/pull/82 (which I'm about to merge) because that big 'Internado' beneath the expanding search blocks is from my last merge and it's NOT supposed to be there lol...

**Comment by frostyshadows** [comment]
Yeah I'll rebase once it's merged then

**Review by stephqwu — APPROVED** [review]

**Comment by AmirNaghibi** [comment]
Looks great! I guess @stephqwu can merge her code and @frostyshadows can pull, resolve the conflicts and push back to her current PR

**Pull request merged**
