### PR TITLE
Landing page with horrible sizing

### PR DESCRIPTION
**Pull request by stephqwu**
Landing page changes. Route establishment was accidentally put through in the previous PR, if this one gets approved I'll fix sizing in the next one

### CODE REVIEW

**Review by AmirNaghibi — APPROVED** [review]
That's fantastic!! maybe add a background color too 💯

**Comment by cowmanjoe** [comment]
Looks good! As Steven said in his PR, we should probably review/merge his larger PR before merging this one though so this stuff doesn't get lost in the conflicts.

**Comment by stephqwu** [comment]
Sounds good! @cowmanjoe 

We'll have to wait haha @AmirNaghibi 

Also which PR are we talking about? I would love to subscribe so I know when it gets merged

**Comment by AmirNaghibi** [comment]
We have to do a review on the following PR:
https://github.com/ubclaunchpad/Internado/pull/85

**Pull request merged**
