### PR TITLE
135 - Fixed search API 500 error with empty keywords 

### PR DESCRIPTION
**Pull request by cowmanjoe**
I just added a small check to see if the keywords were empty and if so, returned an empty array. I think this makes sense because it avoids exceptional return values (i.e. 400 response).

### CODE REVIEW

**Comment by frostyshadows** [comment]
Returning a 400 makes more sense imo, because the front end could get the 400 and still display en empty list but also give some indication to the user what went wrong. For example, maybe the search box could get highlighted in red.

**Comment by cowmanjoe** [comment]
@frostyshadows Sounds good to me!

**Comment by cowmanjoe** [comment]
Should be fixed now. Just an FYI: the 400 response for empty string will be returned for any string that is just whitespace and ampersands. This is because of the way that Postgres handles text search. Essentially, the search query needs to be transformed into "word1 & word2 & word3". My implementation ignores any ampersands and extra whitespace to convert something like "foo   bar baz && biz &&&" to "foo & bar & baz & biz". 

I don't see this being a big issue so I don't think we need to worry about it now.

**Review by frostyshadows — APPROVED** [review]
LGTM 🎄

**Pull request merged**
